name: quadruped_pympc_env
channels:
- conda-forge
- nvidia
- robostack-staging
dependencies:
- pip
- python
- casadi
- numpy
- matplotlib
- jaxlib=*=*cuda*
- jax
- cuda-nvcc 
- meshcat-python 
- scipy 
- pinocchio
- adam-robotics[all]
- compilers 
- cmake 
- pkg-config 
- make 
- tqdm
- gymnasium
- pip:
  - mujoco
  - readchar
  - liecasadi

